### ISSUE TITLE
Label date

### ISSUE THREAD

**Issue by celian-rib** [tjobit/bot-agenda#1]
Devoir posté le 10/01
Date du devoir 26/05
Label : Pour dans un mois 👎🏻
(Le devoir est dans 4-5 mois)
![image](https://user-images.githubusercontent.com/38594012/104130154-83a47300-536f-11eb-9f4f-9c10003e33ce.png)

**Comment by kr4xkan** [comment]
(en plus c'est mon anniversaire quoi)
